on:
  pull:
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get lasted code
      uses: actions/checkout@v3

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with: 
        server: novaldigital.com
        username: ${{ secrets.ftp_username}}
        password: ${{ secrets.ftp_password}}
        server-dir: /public_html/test/
